version: "3.8"

#see https://forums.docker.com/t/data-directory-var-lib-postgresql-data-pgdata-has-wrong-ownership/17963/26
services:
  db:
    container_name: PROJECT_NAME_db_1
    image: postgres:latest
    #build: pgres #see https://stackoverflow.com/a/66502465/5122790
    volumes:
      - ../django_data/db:/var/lib/postgresql/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=<your_value_here>
      - POSTGRES_USER=<your_value_here>
      - POSTGRES_PASSWORD=<your_value_here>
      - PGDATA=/var/lib/postgresql/data/pgdata #see https://stackoverflow.com/a/61884120/5122790 https://stackoverflow.com/a/66502465/5122790

  pgres_adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

  backend:
    container_name: PROJECT_NAME_backend_1
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - uid=${COMPOSE_UID:-1000}
        - gid=${COMPOSE_GID:-1000}
    volumes:
      - ../src/:/opt/PROJECT_NAME/
      - ../data/:/opt/data/
      - ../django_data/:/opt/django_data/
      #- ../django_data/collected_static:/opt/django_data/collected_static
      #- ../django_data/media:/opt/django_data/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
     - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-settings.development}
    restart: unless-stopped
    command: entrypoint_dev.sh

#  tf_serving:
#    container_name: PROJECT_NAME_tfserving_1
#    image: tensorflow/serving
#    ports:
#      - "8501:8501"
#      - "8500:8500"
#    depends_on:
#      - backend
#    volumes:
#      - ../data/<your_tfserving_modelname>/:/models/<your_tfserving_modelname>/
#    environment:
#      - MODEL_NAME=<your_tfserving_modelname>